import { app, Menu, nativeImage, Tray } from 'electron';
import path from 'node:path';
import type { ConnectionState } from '../shared/connectionState';
import type { VpnController } from './vpn/vpnController';

const APP_NAME = 'NextGen VPN'; // matches the BrowserWindow title set in index.ts

/**
 * Menu-bar/system-tray icon (product ask: quick connect/disconnect "near the
 * clock" without opening the main window). Electron's Tray API is used as-is
 * — it's cross-platform (Windows/Linux get an equivalent notification-area
 * icon) — with only one macOS/Windows-specific wrinkle called out below
 * (template images).
 *
 * One padlock glyph (generated by scripts/generate-tray-icons.mjs into
 * resources/tray/, since this app has no other icon asset to derive tray
 * icons from), recolored per ConnectionState — same palette the renderer
 * already uses for state text (design-tokens/tokens.mjs `state.*`):
 *   DISCONNECTED            -> template image (monochrome, alpha-only)
 *   CONNECTING/RECONNECTING -> amber
 *   CONNECTED               -> green
 *   ERROR/OPERATOR_BLOCKED  -> red
 *
 * "Template" images are a macOS convention (nativeImage#setTemplateImage):
 * the OS ignores the image's RGB and paints it using the current menu-bar
 * foreground color, so it automatically matches light/dark menu bar themes
 * and the "reduce transparency" appearance. It only makes sense for the
 * neutral/idle icon, since macOS *ignores color* on template images — that's
 * exactly why the other four states use plain (non-template) colored icons
 * instead: color is the whole point there. Windows/Linux ignore
 * setTemplateImage entirely and just render the PNG as given, so this is a
 * cosmetic no-op rather than a platform branch.
 */

const ICON_BY_STATE: Record<ConnectionState, { file: string; template: boolean }> = {
  DISCONNECTED: { file: 'tray-disconnected.png', template: true },
  CONNECTING: { file: 'tray-connecting.png', template: false },
  CONNECTED: { file: 'tray-connected.png', template: false },
  RECONNECTING: { file: 'tray-reconnecting.png', template: false },
  OPERATOR_BLOCKED: { file: 'tray-blocked.png', template: false },
  ERROR: { file: 'tray-error.png', template: false },
};

// Tray-only strings. Deliberately not shared with src/renderer/src/i18n.ts:
// that module keys off `navigator.language`, which doesn't exist in the main
// process, and pulling renderer code into main for a handful of menu labels
// isn't worth the coupling. Kept minimal and mirrors the renderer's wording.
const LANG = app.getLocale().toLowerCase().startsWith('ru') ? 'ru' : 'en';
const L = {
  ru: {
    status: {
      DISCONNECTED: 'Отключено',
      CONNECTING: 'Подключение…',
      CONNECTED: 'Защищено',
      RECONNECTING: 'Переподключение…',
      OPERATOR_BLOCKED: 'Заблокировано оператором',
      ERROR: 'Ошибка подключения',
    } satisfies Record<ConnectionState, string>,
    connect: 'Подключить',
    disconnect: 'Отключить',
    open: (name: string) => `Открыть ${name}`,
    quit: 'Выйти',
  },
  en: {
    status: {
      DISCONNECTED: 'Disconnected',
      CONNECTING: 'Connecting…',
      CONNECTED: 'Protected',
      RECONNECTING: 'Reconnecting…',
      OPERATOR_BLOCKED: 'Blocked by carrier',
      ERROR: 'Connection error',
    } satisfies Record<ConnectionState, string>,
    connect: 'Connect',
    disconnect: 'Disconnect',
    open: (name: string) => `Open ${name}`,
    quit: 'Quit',
  },
}[LANG];

function resolveTrayIconPath(file: string): string {
  // Same dev-vs-packaged resolution pattern as getXrayBinaryPath/getGeoDataDir
  // in xray/binaryManager.ts. Packaged builds get resources/tray/ via
  // package.json "build.extraResources"; in dev it's read straight from the repo.
  return app.isPackaged
    ? path.join(process.resourcesPath, 'tray', file)
    : path.join(app.getAppPath(), 'resources', 'tray', file);
}

function loadIcon(state: ConnectionState) {
  const { file, template } = ICON_BY_STATE[state];
  // nativeImage.createFromPath auto-pairs "<file>@2x.png" sitting next to
  // "<file>" for retina displays — both are generated by generate-tray-icons.mjs.
  const image = nativeImage.createFromPath(resolveTrayIconPath(file));
  image.setTemplateImage(template);
  return image;
}

export interface TrayHandle {
  tray: Tray;
  destroy: () => void;
}

/**
 * @param showMainWindow shows/focuses the main window, creating one if needed (index.ts owns window creation).
 */
export function createAppTray(vpn: VpnController, showMainWindow: () => void): TrayHandle {
  let state: ConnectionState = vpn.getState();
  let region: string | null = null;

  const tray = new Tray(loadIcon(state));
  applyTooltip();

  // Left-click = quick toggle (the whole point of the tray, per the product
  // ask: connect/disconnect without opening the window). Deliberately not
  // wired via Tray#setContextMenu, which on macOS/Windows binds the *same*
  // menu to left- and right-click — that would make a distinct left-click
  // action impossible. Right-click gets its own popup menu below instead.
  //
  // Note (Linux): AppIndicator-based trays (Ubuntu's default) always show a
  // menu and never emit 'click'/'right-click' — a known Electron limitation,
  // not something fixable from app code. Left-click quick-toggle degrades to
  // "use the menu's Connect/Disconnect item" there; the API is still used
  // the standard cross-platform way.
  tray.on('click', () => {
    void toggleConnection();
  });
  tray.on('right-click', () => {
    tray.popUpContextMenu(buildMenu());
  });

  function toggleConnection(): Promise<void> {
    return state === 'CONNECTED' || state === 'CONNECTING' || state === 'RECONNECTING'
      ? vpn.disconnect()
      : vpn.connect();
  }

  function applyTooltip(): void {
    const statusLine = L.status[state];
    tray.setToolTip(region ? `${APP_NAME} — ${statusLine} (${region})` : `${APP_NAME} — ${statusLine}`);
  }

  function buildMenu(): Menu {
    const isActive = state === 'CONNECTED' || state === 'CONNECTING' || state === 'RECONNECTING';
    return Menu.buildFromTemplate([
      { label: L.status[state], enabled: false },
      { type: 'separator' },
      {
        label: isActive ? L.disconnect : L.connect,
        click: () => void toggleConnection(),
      },
      { type: 'separator' },
      { label: L.open(APP_NAME), click: () => showMainWindow() },
      { type: 'separator' },
      { label: L.quit, click: () => app.quit() },
    ]);
  }

  const onState = (next: ConnectionState): void => {
    state = next;
    tray.setImage(loadIcon(state));
    applyTooltip();
  };
  const onRegion = (next: string | null): void => {
    region = next;
    applyTooltip();
  };
  vpn.on('state', onState);
  vpn.on('region', onRegion);

  return {
    tray,
    destroy: () => {
      vpn.off('state', onState);
      vpn.off('region', onRegion);
      tray.destroy();
    },
  };
}
