import { app, Menu, nativeImage, Notification, Tray, type MenuItemConstructorOptions } from 'electron';
import path from 'node:path';
import type { ConnectionState } from '../shared/connectionState';
import type { ApiClient } from './api/apiClient';
import type { RelayMode } from './p2p/relayAgent';
import { RELAY_UNSUPPORTED_PREFIX, type RelayManager } from './p2p/relayManager';
import type { VpnController } from './vpn/vpnController';

const HOUR_MS = 60 * 60 * 1000;

const APP_NAME = 'Aura VPN'; // matches the BrowserWindow title set in index.ts

/**
 * Menu-bar/system-tray icon (product ask: quick connect/disconnect "near the
 * clock" without opening the main window). Electron's Tray API is used as-is
 * — it's cross-platform (Windows/Linux get an equivalent notification-area
 * icon) — with only one macOS/Windows-specific wrinkle called out below
 * (template images).
 *
 * One padlock glyph (generated by scripts/generate-tray-icons.mjs into
 * resources/tray/, since this app has no other icon asset to derive tray
 * icons from), recolored per ConnectionState — same palette the renderer
 * already uses for state text (design-tokens/tokens.mjs `state.*`):
 *   DISCONNECTED            -> template image (monochrome, alpha-only)
 *   CONNECTING/RECONNECTING -> amber
 *   CONNECTED               -> green
 *   ERROR/OPERATOR_BLOCKED  -> red
 *
 * "Template" images are a macOS convention (nativeImage#setTemplateImage):
 * the OS ignores the image's RGB and paints it using the current menu-bar
 * foreground color, so it automatically matches light/dark menu bar themes
 * and the "reduce transparency" appearance. It only makes sense for the
 * neutral/idle icon, since macOS *ignores color* on template images — that's
 * exactly why the other four states use plain (non-template) colored icons
 * instead: color is the whole point there. Windows/Linux ignore
 * setTemplateImage entirely and just render the PNG as given, so this is a
 * cosmetic no-op rather than a platform branch.
 */

const ICON_BY_STATE: Record<ConnectionState, { file: string; template: boolean }> = {
  DISCONNECTED: { file: 'tray-disconnected.png', template: true },
  CONNECTING: { file: 'tray-connecting.png', template: false },
  CONNECTED: { file: 'tray-connected.png', template: false },
  RECONNECTING: { file: 'tray-reconnecting.png', template: false },
  OPERATOR_BLOCKED: { file: 'tray-blocked.png', template: false },
  ERROR: { file: 'tray-error.png', template: false },
};

// Tray-only strings. Deliberately not shared with src/renderer/src/i18n.ts:
// that module keys off `navigator.language`, which doesn't exist in the main
// process, and pulling renderer code into main for a handful of menu labels
// isn't worth the coupling. Kept minimal and mirrors the renderer's wording.
const LANG = app.getLocale().toLowerCase().startsWith('ru') ? 'ru' : 'en';
const L = {
  ru: {
    status: {
      DISCONNECTED: 'Отключено',
      CONNECTING: 'Подключение…',
      CONNECTED: 'Защищено',
      RECONNECTING: 'Переподключение…',
      OPERATOR_BLOCKED: 'Заблокировано оператором',
      ERROR: 'Ошибка подключения',
    } satisfies Record<ConnectionState, string>,
    connect: 'Подключить',
    disconnect: 'Отключить',
    open: (name: string) => `Открыть ${name}`,
    quit: 'Выйти',
    p2pOff: 'P2P-раздача: выключена',
    p2pAlways: 'P2P-раздача: включена всегда',
    p2pUntil: (time: string) => `P2P-раздача: включена до ${time}`,
    p2pUnsupported: 'P2P-раздача: не поддерживается в этой сети',
    p2pSetOff: 'Выключить',
    p2p1h: 'На 1 час',
    p2p8h: 'На 8 часов',
    p2pSetAlways: 'Всегда',
    p2pInApp: 'Включить P2P-раздачу в приложении…',
    p2pUnsupportedTitle: 'С этой сети раздача не поддерживается',
    p2pUnsupportedBody:
      'Провайдер не пропускает прямые подключения к устройству. С другой сети — например, домашнего Wi‑Fi — раздача может работать.',
  },
  en: {
    status: {
      DISCONNECTED: 'Disconnected',
      CONNECTING: 'Connecting…',
      CONNECTED: 'Protected',
      RECONNECTING: 'Reconnecting…',
      OPERATOR_BLOCKED: 'Blocked by carrier',
      ERROR: 'Connection error',
    } satisfies Record<ConnectionState, string>,
    connect: 'Connect',
    disconnect: 'Disconnect',
    open: (name: string) => `Open ${name}`,
    quit: 'Quit',
    p2pOff: 'P2P relaying: off',
    p2pAlways: 'P2P relaying: always on',
    p2pUntil: (time: string) => `P2P relaying: on until ${time}`,
    p2pUnsupported: 'P2P relaying: not supported on this network',
    p2pSetOff: 'Turn off',
    p2p1h: 'For 1 hour',
    p2p8h: 'For 8 hours',
    p2pSetAlways: 'Always',
    p2pInApp: 'Turn on P2P relaying in the app…',
    p2pUnsupportedTitle: 'Relaying isn’t supported on this network',
    p2pUnsupportedBody:
      'Your provider doesn’t let direct connections reach this device. On another network — home Wi‑Fi, say — relaying may work.',
  },
}[LANG];

function resolveTrayIconPath(file: string): string {
  // Same dev-vs-packaged resolution pattern as getXrayBinaryPath/getGeoDataDir
  // in xray/binaryManager.ts. Packaged builds get resources/tray/ via
  // package.json "build.extraResources"; in dev it's read straight from the repo.
  return app.isPackaged
    ? path.join(process.resourcesPath, 'tray', file)
    : path.join(app.getAppPath(), 'resources', 'tray', file);
}

function loadIcon(state: ConnectionState) {
  const { file, template } = ICON_BY_STATE[state];
  // nativeImage.createFromPath auto-pairs "<file>@2x.png" sitting next to
  // "<file>" for retina displays — both are generated by generate-tray-icons.mjs.
  const image = nativeImage.createFromPath(resolveTrayIconPath(file));
  image.setTemplateImage(template);
  return image;
}

export type TrayStrings = typeof L;

export interface RelayModeView {
  mode: RelayMode;
  expiresAtEpochMs: number | null;
  durationMs: number | null;
  unsupportedNetwork: 'SYMMETRIC' | 'NO_UDP' | null;
}

/** The status line for the relay, also used in the tooltip. */
export function p2pStatusLine(m: RelayModeView, s: TrayStrings = L): string {
  if (m.unsupportedNetwork && m.mode === 'OFF') return s.p2pUnsupported;
  if (m.mode === 'ALWAYS') return s.p2pAlways;
  if (m.mode === 'TIMED' && m.expiresAtEpochMs) {
    return s.p2pUntil(new Date(m.expiresAtEpochMs).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }));
  }
  return s.p2pOff;
}

/**
 * The relay part of the tray menu: its status, and the same four choices as
 * the in-app section. Where this account can't relay yet (a guest, or terms
 * not accepted — the consent belongs in the window), one item opens the app.
 */
export function p2pMenuItems(
  m: RelayModeView,
  canRelayFromTray: boolean,
  actions: { setMode: (mode: RelayMode, durationMs?: number) => void; openApp: () => void },
  s: TrayStrings = L
): MenuItemConstructorOptions[] {
  const status: MenuItemConstructorOptions = { label: p2pStatusLine(m, s), enabled: false };
  if (!canRelayFromTray) {
    return [status, { label: s.p2pInApp, click: () => actions.openApp() }];
  }
  const timed = (hours: number) => m.mode === 'TIMED' && (m.durationMs ?? 0) === hours * HOUR_MS;
  return [
    status,
    { label: s.p2pSetOff, type: 'radio', checked: m.mode === 'OFF', click: () => actions.setMode('OFF') },
    { label: s.p2p1h, type: 'radio', checked: timed(1), click: () => actions.setMode('TIMED', HOUR_MS) },
    { label: s.p2p8h, type: 'radio', checked: timed(8), click: () => actions.setMode('TIMED', 8 * HOUR_MS) },
    { label: s.p2pSetAlways, type: 'radio', checked: m.mode === 'ALWAYS', click: () => actions.setMode('ALWAYS') },
  ];
}

export interface TrayHandle {
  tray: Tray;
  destroy: () => void;
}

/**
 * @param showMainWindow shows/focuses the main window, creating one if needed (index.ts owns window creation).
 */
export function createAppTray(
  vpn: VpnController,
  showMainWindow: () => void,
  relayManager: RelayManager,
  apiClient: ApiClient
): TrayHandle {
  let state: ConnectionState = vpn.getState();
  let region: string | null = null;
  // Whether relaying can be switched from here — refreshed on every menu
  // open (a guest, a signed-out app, or terms not yet accepted can't).
  let canRelayFromTray = false;

  const tray = new Tray(loadIcon(state));
  applyTooltip();

  // Left-click = quick toggle (the whole point of the tray, per the product
  // ask: connect/disconnect without opening the window). Deliberately not
  // wired via Tray#setContextMenu, which on macOS/Windows binds the *same*
  // menu to left- and right-click — that would make a distinct left-click
  // action impossible. Right-click gets its own popup menu below instead.
  //
  // Note (Linux): AppIndicator-based trays (Ubuntu's default) always show a
  // menu and never emit 'click'/'right-click' — a known Electron limitation,
  // not something fixable from app code. Left-click quick-toggle degrades to
  // "use the menu's Connect/Disconnect item" there; the API is still used
  // the standard cross-platform way.
  tray.on('click', () => {
    void toggleConnection();
  });
  tray.on('right-click', () => {
    // A quick status check first, capped so the menu never waits long.
    void Promise.race([
      apiClient
        .getP2pRelayStatus()
        .then((st) => (canRelayFromTray = !st.isGuest && st.termsAccepted))
        .catch(() => (canRelayFromTray = false)),
      new Promise((r) => setTimeout(r, 1500)),
    ]).then(() => tray.popUpContextMenu(buildMenu()));
  });

  function setRelayMode(mode: RelayMode, durationMs?: number): void {
    const expiresAt = durationMs ? Date.now() + durationMs : null;
    relayManager.setMode(mode, expiresAt, durationMs).catch((err: unknown) => {
      const message = err instanceof Error ? err.message : String(err);
      if (message.startsWith(RELAY_UNSUPPORTED_PREFIX)) {
        if (Notification.isSupported()) {
          new Notification({ title: L.p2pUnsupportedTitle, body: L.p2pUnsupportedBody }).show();
        }
        return;
      }
      console.warn('[tray] relay mode change failed', err);
      showMainWindow();
    });
  }

  function toggleConnection(): Promise<void> {
    return state === 'CONNECTED' || state === 'CONNECTING' || state === 'RECONNECTING'
      ? vpn.disconnect()
      : vpn.connect();
  }

  function applyTooltip(): void {
    const statusLine = L.status[state];
    const vpnLine = region ? `${APP_NAME} — ${statusLine} (${region})` : `${APP_NAME} — ${statusLine}`;
    tray.setToolTip(`${vpnLine}\n${p2pStatusLine(relayManager.getMode())}`);
  }

  function buildMenu(): Menu {
    const isActive = state === 'CONNECTED' || state === 'CONNECTING' || state === 'RECONNECTING';
    return Menu.buildFromTemplate([
      { label: L.status[state], enabled: false },
      { type: 'separator' },
      {
        label: isActive ? L.disconnect : L.connect,
        click: () => void toggleConnection(),
      },
      { type: 'separator' },
      ...p2pMenuItems(relayManager.getMode(), canRelayFromTray, { setMode: setRelayMode, openApp: showMainWindow }),
      { type: 'separator' },
      { label: L.open(APP_NAME), click: () => showMainWindow() },
      { type: 'separator' },
      { label: L.quit, click: () => app.quit() },
    ]);
  }

  const onState = (next: ConnectionState): void => {
    state = next;
    tray.setImage(loadIcon(state));
    applyTooltip();
  };
  const onRegion = (next: string | null): void => {
    region = next;
    applyTooltip();
  };
  vpn.on('state', onState);
  vpn.on('region', onRegion);
  const onRelayMode = (): void => applyTooltip();
  relayManager.on('modeChanged', onRelayMode);

  return {
    tray,
    destroy: () => {
      vpn.off('state', onState);
      vpn.off('region', onRegion);
      relayManager.off('modeChanged', onRelayMode);
      tray.destroy();
    },
  };
}
