-- Hibernate's own ddl-auto (create-drop, application-test.yml) fails to
-- create the "nodes" table under H2: Node#realityShortIds uses
-- @Column(columnDefinition = "text[]") — real Postgres array syntax H2's
-- parser doesn't accept (it wants "<type> ARRAY", not "<type>[]"). No test
-- before P2pNodeLifecycleIntegrationTest ever exercised a real Node entity
-- against a real datasource (every other Node-touching test mocks
-- NodeRepository), so this was never noticed. Fixing Node's own column
-- mapping is out of scope here — production uses ddl-auto: validate, so
-- changing that annotation risks a real startup validation failure against
-- the actual Postgres schema. This is the exact DDL Hibernate itself
-- attempted (see the "GenerationTarget encountered exception" warning it
-- logs when create-drop fails on this one table), with only the one
-- offending column's type swapped for an H2-legal equivalent — an
-- H2-only stand-in, IF NOT EXISTS so it's a harmless no-op everywhere else
-- (every other entity's table IS created fine by Hibernate itself).
CREATE TABLE IF NOT EXISTS nodes (
    id bigint generated by default as identity,
    active_connections integer,
    available_to_paid boolean not null,
    available_to_trial boolean not null,
    cpu_count integer,
    cpu_percent numeric(5,2),
    recent_bytes_per_sec float(53),
    config_version bigint not null,
    created_at timestamp(6) with time zone not null,
    last_heartbeat_at timestamp(6) with time zone,
    last_traffic_stats_at timestamp(6) with time zone,
    memory_total_bytes bigint,
    memory_used_bytes bigint,
    owner_user_id bigint,
    relay_expires_at timestamp(6) with time zone,
    total_bytes_served bigint not null,
    updated_at timestamp(6) with time zone not null,
    relay_mode varchar(16) not null,
    pool varchar(32) not null,
    status varchar(32) not null,
    type varchar(32) not null,
    asn varchar(64),
    current_config_hash varchar(64),
    public_ip varchar(64) not null,
    region varchar(64) not null,
    reality_private_key varchar(128),
    reality_public_key varchar(128),
    hostname varchar(255) not null unique,
    reality_short_ids character varying array,
    primary key (id)
);
