import React from 'react';
import { ArrowLeft } from 'lucide-react';
import { Lang } from '../i18n';

export type LegalDoc = 'privacy' | 'terms';

interface Section {
  heading: string;
  body: string[];
}

interface Content {
  title: string;
  updated: string;
  intro: string;
  sections: Section[];
}

// Long-form prose lives here, not in i18n.ts, for the same reason as
// P2pRelayTermsPage: a document, not UI chrome. Written to match what the
// code actually stores (see docs/ARCHITECTURE.md, docs/DIAGNOSTICS.md).
const DOCS: Record<LegalDoc, Record<Lang, Content>> = {
  privacy: {
    ru: {
      title: 'Политика конфиденциальности',
      updated: 'Редакция от 2026-09-24',
      intro:
        'Здесь описано, какие данные Aura VPN хранит, зачем и как их удалить. Коротко: мы не записываем, какие сайты вы открываете, и не храним содержимое трафика.',
      sections: [
        {
          heading: '1. Что мы не храним',
          body: [
            'Историю посещений, DNS-запросы, адреса назначения и содержимое трафика. Ноды пропускают трафик, но не пишут, куда он идёт.',
          ],
        },
        {
          heading: '2. Что мы храним',
          body: [
            'Данные для входа: email и хеш пароля, либо идентификатор Telegram или Google — смотря как вы вошли. Для входа из приложения без регистрации — случайный идентификатор, созданный приложением.',
            'Устройства: название и платформа, которые сообщает приложение, дата добавления и последнего подключения.',
            'Счётчик трафика — число байт за период. Без него нельзя считать квоту тарифа.',
            'Платежи: суммы, баланс, история списаний и пополнений, хеши крипто-транзакций, платежи Telegram Stars.',
            'IP-адреса, с которых открывают ссылку-подписку, — короткое время, чтобы заметить утечку ссылки и сменить ключи.',
            'Отчёты об ошибках приложений и нод (тип ошибки, версия, платформа) — чтобы чинить сбои. В них нет адресов, которые вы посещаете.',
          ],
        },
        {
          heading: '3. Зачем',
          body: [
            'Чтобы предоставлять VPN, считать трафик и оплату, защищать аккаунт и исправлять ошибки. Данные не продаются и не передаются третьим лицам для рекламы.',
          ],
        },
        {
          heading: '4. Сторонние сервисы',
          body: [
            'Telegram (вход, уведомления, оплата звёздами), Google (вход), блокчейн-сети TRON и Ethereum (оплата USDT — транзакции в них публичны по своей природе), GitHub (загрузка приложений).',
          ],
        },
        {
          heading: '5. Удаление',
          body: [
            'Аккаунт можно удалить в личном кабинете на сайте (раздел «Аккаунт»). Удаляются email, пароль, привязки Telegram и Google, устройства и ключи; ссылка-подписка перестаёт работать. Записи о платежах остаются в обезличенном виде, так как нужны для учёта. Остаток баланса при удалении сгорает.',
          ],
        },
        {
          heading: '6. Контакты',
          body: ['Вопросы о данных — через ссылку «Поддержка» внизу страницы.'],
        },
      ],
    },
    en: {
      title: 'Privacy Policy',
      updated: 'Revision of 2026-09-24',
      intro:
        'What Aura VPN stores, why, and how to delete it. In short: we do not record which sites you visit and do not store the contents of your traffic.',
      sections: [
        { heading: '1. What we do not store', body: ['Browsing history, DNS queries, destination addresses, or traffic contents. Nodes pass traffic through without logging where it goes.'] },
        {
          heading: '2. What we store',
          body: [
            'Sign-in data: email and password hash, or your Telegram or Google identifier, depending on how you signed in. For app sign-in without registration, a random identifier generated by the app.',
            'Devices: the name and platform the app reports, when it was added and last connected.',
            'A traffic counter — bytes per period — needed to enforce the plan quota.',
            'Payments: amounts, balance, debit/top-up history, crypto transaction hashes, Telegram Stars payments.',
            'IP addresses that open your subscription link, briefly, to detect a leaked link and rotate keys.',
            'Error reports from apps and nodes (error type, version, platform) to fix failures. They contain no addresses you visit.',
          ],
        },
        { heading: '3. Why', body: ['To provide the VPN, count traffic and payments, protect the account, and fix bugs. Data is not sold or shared for advertising.'] },
        { heading: '4. Third parties', body: ['Telegram (sign-in, notifications, Stars payments), Google (sign-in), the TRON and Ethereum networks (USDT payments — public by nature), GitHub (app downloads).'] },
        { heading: '5. Deletion', body: ['Delete your account in the web dashboard (Account section). Email, password, Telegram and Google links, devices and keys are removed; the subscription link stops working. Payment records remain in anonymised form for accounting. Any remaining balance is forfeited.'] },
        { heading: '6. Contact', body: ['Questions about your data: use the Support link at the bottom of the page.'] },
      ],
    },
  },
  terms: {
    ru: {
      title: 'Условия использования',
      updated: 'Редакция от 2026-09-24',
      intro:
        'Пользуясь Aura VPN, вы соглашаетесь с этими условиями. Пожалуйста, прочитайте раздел об оплате.',
      sections: [
        {
          heading: '1. Сервис',
          body: [
            'Aura VPN — сервис защищённого подключения к интернету. Мы стараемся, чтобы он работал всегда, но не гарантируем доступность при блокировках, отключениях связи и в других обстоятельствах вне нашего контроля.',
          ],
        },
        {
          heading: '2. Пробный период',
          body: ['Пробный период — 1 ГБ трафика без ограничения по времени, один раз на аккаунт.'],
        },
        {
          heading: '3. Оплата',
          body: [
            'Тарифы оплачиваются с внутреннего баланса, который пополняется в USDT, Telegram Stars или промокодом. Цены указаны на сайте.',
            'Тариф действует 30 дней (годовой — 365 дней, трафик выдаётся на каждые 30 дней). В конце срока тариф продлевается автоматически, если на балансе хватает средств; иначе VPN останавливается до оплаты. Мы предупреждаем о нехватке заранее.',
            'Переход на более дешёвый тариф начинается с конца оплаченного срока, на более дорогой — сразу.',
            'Возврат средств с баланса или за неиспользованный период рассматривается по обращению в поддержку.',
          ],
        },
        {
          heading: '4. Правила',
          body: [
            'Нельзя использовать сервис для атак, рассылки спама, распространения вредоносного ПО и другой незаконной деятельности, а также передавать ссылку-подписку другим людям. За нарушения аккаунт может быть заблокирован.',
            'Вы сами отвечаете за соблюдение законов страны, в которой находитесь.',
          ],
        },
        {
          heading: '5. Аккаунт',
          body: [
            'Вы можете удалить аккаунт в любой момент в личном кабинете; остаток баланса при этом сгорает.',
          ],
        },
        {
          heading: '6. Поддержка',
          body: ['Ссылка «Поддержка» — внизу страницы.'],
        },
      ],
    },
    en: {
      title: 'Terms of Use',
      updated: 'Revision of 2026-09-24',
      intro: 'By using Aura VPN you agree to these terms. Please read the payment section.',
      sections: [
        { heading: '1. The service', body: ['Aura VPN provides a secure internet connection. We work to keep it available but cannot guarantee it during blocking, network shutdowns, or other events outside our control.'] },
        { heading: '2. Trial', body: ['The trial is 1 GB of traffic with no time limit, once per account.'] },
        {
          heading: '3. Payment',
          body: [
            'Plans are paid from an in-app balance topped up with USDT, Telegram Stars or a promo code. Prices are shown on the site.',
            'A plan lasts 30 days (annual: 365 days, with traffic granted every 30 days). At the end it renews automatically if the balance covers it; otherwise the VPN stops until paid. We warn you ahead of a shortfall.',
            'A move to a cheaper plan starts when the paid period ends; to a pricier one, at once.',
            'Refunds of the balance or of an unused period are handled on request to support.',
          ],
        },
        { heading: '4. Rules', body: ['Do not use the service for attacks, spam, malware or other unlawful activity, or share your subscription link with others. Violations may lead to the account being blocked.', 'You are responsible for complying with the laws of the country you are in.'] },
        { heading: '5. Account', body: ['You can delete your account at any time in the dashboard; any remaining balance is forfeited.'] },
        { heading: '6. Support', body: ['The Support link is at the bottom of the page.'] },
      ],
    },
  },
};

export const LegalPage: React.FC<{ doc: LegalDoc; lang: Lang; onBack: () => void }> = ({ doc, lang, onBack }) => {
  const c = DOCS[doc][lang];
  return (
    <div className="w-full max-w-3xl mx-auto px-4 py-8 space-y-6">
      <button onClick={onBack} className="inline-flex items-center gap-2 text-xs text-slate-400 hover:text-white">
        <ArrowLeft className="w-4 h-4" />
        {lang === 'ru' ? 'Назад' : 'Back'}
      </button>
      <div>
        <h1 className="text-2xl font-bold tracking-tight">{c.title}</h1>
        <p className="text-xs text-slate-500 mt-1">{c.updated}</p>
      </div>
      <p className="text-sm text-slate-300 leading-relaxed">{c.intro}</p>
      {c.sections.map((sec) => (
        <section key={sec.heading} className="space-y-2">
          <h2 className="text-base font-semibold">{sec.heading}</h2>
          {sec.body.map((p) => (
            <p key={p} className="text-sm text-slate-400 leading-relaxed">{p}</p>
          ))}
        </section>
      ))}
    </div>
  );
};
